jdk: oraclejdk8
language: scala
scala:
- 2.11.11
- 2.12.2
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
  - "$HOME/.m2"
script:
- sbt -DscalaVersion=$TRAVIS_SCALA_VERSION assembly
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_KEY
  file_glob: true
  file: target/scala-*/kafka-connect-iothub-assembly_*.jar
  skip_cleanup: true
  on:
    branch: master
    scala: '2.11.11'
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
